FROM docker.io/golang:1.25.1-alpine

# Install deps
RUN apk add --no-cache git build-base

WORKDIR /app

# Copy dependency files first
COPY go.mod go.sum ./
RUN go mod download

# Install air
RUN go install github.com/air-verse/air@latest

# Copy source code
COPY . .

# Generate Prisma client
RUN go run github.com/steebchen/prisma-client-go generate

# Expose API port
EXPOSE 8080

# Run using air
CMD ["air", "-c", ".air.toml"]
